/* 
 * YouLend Third Party Instant Settlement API
 *
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using YL.Web.Api.ThirdParty.InstantSettlement.Client.Client;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Api;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Model;

namespace YL.Web.Api.ThirdParty.InstantSettlement.Client.Test
{
    /// <summary>
    ///  Class for testing InstantSettlementApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class InstantSettlementApiTests : IDisposable
    {
        private InstantSettlementApi instance;

        public InstantSettlementApiTests()
        {
            instance = new InstantSettlementApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstantSettlementApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InstantSettlementApi
            //Assert.IsType(typeof(InstantSettlementApi), instance, "instance is a InstantSettlementApi");
        }

        
        /// <summary>
        /// Test ApiInstantSettlementGet
        /// </summary>
        [Fact]
        public void ApiInstantSettlementGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiVersion = null;
            //var response = instance.ApiInstantSettlementGet(apiVersion);
            //Assert.IsType<List<InstantSettlementView>> (response, "response is List<InstantSettlementView>");
        }
        
        /// <summary>
        /// Test ApiInstantSettlementInstantSettlementNumberPost
        /// </summary>
        [Fact]
        public void ApiInstantSettlementInstantSettlementNumberPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int instantSettlementNumber = null;
            //string apiVersion = null;
            //List<CreateInstantSettlementTransactionModel> createInstantSettlementTransactionModel = null;
            //instance.ApiInstantSettlementInstantSettlementNumberPost(instantSettlementNumber, apiVersion, createInstantSettlementTransactionModel);
            
        }
        
        /// <summary>
        /// Test ApiInstantSettlementInstantSettlementNumberTransactionsGet
        /// </summary>
        [Fact]
        public void ApiInstantSettlementInstantSettlementNumberTransactionsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int instantSettlementNumber = null;
            //string apiVersion = null;
            //var response = instance.ApiInstantSettlementInstantSettlementNumberTransactionsGet(instantSettlementNumber, apiVersion);
            //Assert.IsType<List<InstantSettlementTransactionModel>> (response, "response is List<InstantSettlementTransactionModel>");
        }
        
    }

}
