/* 
 * YouLend Third Party Instant Settlement API
 *
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Api;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Model;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.InstantSettlement.Client.Test
{
    /// <summary>
    ///  Class for testing CreateInstantSettlementTransactionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateInstantSettlementTransactionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateInstantSettlementTransactionModel
        //private CreateInstantSettlementTransactionModel instance;

        public CreateInstantSettlementTransactionModelTests()
        {
            // TODO uncomment below to create an instance of CreateInstantSettlementTransactionModel
            //instance = new CreateInstantSettlementTransactionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateInstantSettlementTransactionModel
        /// </summary>
        [Fact]
        public void CreateInstantSettlementTransactionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateInstantSettlementTransactionModel
            //Assert.IsInstanceOfType<CreateInstantSettlementTransactionModel> (instance, "variable 'instance' is a CreateInstantSettlementTransactionModel");
        }


        /// <summary>
        /// Test the property 'TransactionReferences'
        /// </summary>
        [Fact]
        public void TransactionReferencesTest()
        {
            // TODO unit test for the property 'TransactionReferences'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'TotalSettlementAmount'
        /// </summary>
        [Fact]
        public void TotalSettlementAmountTest()
        {
            // TODO unit test for the property 'TotalSettlementAmount'
        }
        /// <summary>
        /// Test the property 'TransactionDate'
        /// </summary>
        [Fact]
        public void TransactionDateTest()
        {
            // TODO unit test for the property 'TransactionDate'
        }

    }

}
