/* 
 * YouLend Third Party Instant Settlement API
 *
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Api;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Model;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.InstantSettlement.Client.Test
{
    /// <summary>
    ///  Class for testing InstantSettlementTransactionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstantSettlementTransactionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstantSettlementTransactionModel
        //private InstantSettlementTransactionModel instance;

        public InstantSettlementTransactionModelTests()
        {
            // TODO uncomment below to create an instance of InstantSettlementTransactionModel
            //instance = new InstantSettlementTransactionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstantSettlementTransactionModel
        /// </summary>
        [Fact]
        public void InstantSettlementTransactionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InstantSettlementTransactionModel
            //Assert.IsInstanceOfType<InstantSettlementTransactionModel> (instance, "variable 'instance' is a InstantSettlementTransactionModel");
        }


        /// <summary>
        /// Test the property 'InstantSettlementId'
        /// </summary>
        [Fact]
        public void InstantSettlementIdTest()
        {
            // TODO unit test for the property 'InstantSettlementId'
        }
        /// <summary>
        /// Test the property 'InstantSettlementTransactionNumber'
        /// </summary>
        [Fact]
        public void InstantSettlementTransactionNumberTest()
        {
            // TODO unit test for the property 'InstantSettlementTransactionNumber'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Fact]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'DateFunded'
        /// </summary>
        [Fact]
        public void DateFundedTest()
        {
            // TODO unit test for the property 'DateFunded'
        }
        /// <summary>
        /// Test the property 'DateRepaid'
        /// </summary>
        [Fact]
        public void DateRepaidTest()
        {
            // TODO unit test for the property 'DateRepaid'
        }
        /// <summary>
        /// Test the property 'CurrentAmount'
        /// </summary>
        [Fact]
        public void CurrentAmountTest()
        {
            // TODO unit test for the property 'CurrentAmount'
        }
        /// <summary>
        /// Test the property 'FundedAmount'
        /// </summary>
        [Fact]
        public void FundedAmountTest()
        {
            // TODO unit test for the property 'FundedAmount'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

    }

}
