/* 
 * YouLend Third Party Instant Settlement API
 *
 * Through this API you can can create Instant Settlement transactions with YouLend
 *
 * The version of the OpenAPI document: v1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Api;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Model;
using YL.Web.Api.ThirdParty.InstantSettlement.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.InstantSettlement.Client.Test
{
    /// <summary>
    ///  Class for testing InstantSettlementView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstantSettlementViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstantSettlementView
        //private InstantSettlementView instance;

        public InstantSettlementViewTests()
        {
            // TODO uncomment below to create an instance of InstantSettlementView
            //instance = new InstantSettlementView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstantSettlementView
        /// </summary>
        [Fact]
        public void InstantSettlementViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" InstantSettlementView
            //Assert.IsInstanceOfType<InstantSettlementView> (instance, "variable 'instance' is a InstantSettlementView");
        }


        /// <summary>
        /// Test the property 'InstantSettlementId'
        /// </summary>
        [Fact]
        public void InstantSettlementIdTest()
        {
            // TODO unit test for the property 'InstantSettlementId'
        }
        /// <summary>
        /// Test the property 'InstantSettlementNumber'
        /// </summary>
        [Fact]
        public void InstantSettlementNumberTest()
        {
            // TODO unit test for the property 'InstantSettlementNumber'
        }
        /// <summary>
        /// Test the property 'LenderName'
        /// </summary>
        [Fact]
        public void LenderNameTest()
        {
            // TODO unit test for the property 'LenderName'
        }
        /// <summary>
        /// Test the property 'BorrowerName'
        /// </summary>
        [Fact]
        public void BorrowerNameTest()
        {
            // TODO unit test for the property 'BorrowerName'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'SettlementCycleLengthDay'
        /// </summary>
        [Fact]
        public void SettlementCycleLengthDayTest()
        {
            // TODO unit test for the property 'SettlementCycleLengthDay'
        }

    }

}
